{% set name = "scholarly" %}
{% set version = "1.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 87de2543d904397caa6e448bbf75feaccb6d28d68a1e2c2d4d059d303ef2a355

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6

  run:
    - arrow
    - beautifulsoup4
    - bibtexparser
    - deprecated
    - fake-useragent
    - free-proxy
    - python >=3.6
    - python-dotenv
    - PySocks
    - requests
    - selenium
    - sphinx_rtd_theme
    - typing_extensions

test:
  imports:
    - scholarly

about:
  home: https://github.com/scholarly-python-package/scholarly
  license: Unlicense
  license_family: OTHER
  license_file: LICENSE.txt
  summary: Simple access to Google Scholar authors and citations
  doc_url: https://scholarly.readthedocs.io/
  dev_url: https://github.com/scholarly-python-package/scholarly

extra:
  recipe-maintainers:
    - arunkannawadi
